#!/usr/bin/env bash

if [ -n "$CONFILEFILE" ]; then
    proxysql -f --idle-threads -D /var/lib/proxysql -c $CONFILEFILE 1>/dev/stdout 2>&1 |while IFS= read -r line; do echo "$line" | grep -q 'ERROR' && echo "$line" >&2 || echo "$line"; done
fi
proxysql -f --idle-threads -D /var/lib/proxysql 1>/dev/stdout 2>&1 |while IFS= read -r line; do echo "$line" | grep -q 'ERROR' && echo "$line" >&2 || echo "$line"; done
